apiVersion: v1
kind: PersistentVolume
metadata:
  name: shared-pv
  namespace: tp-app
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  storageClassName: nfs-rwx
  nfs:
    path: /tp_share           # chemin du partage Filestore
    server: 10.91.111.170     # remplace par l'IP de ton Filestore
  persistentVolumeReclaimPolicy: Retain

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: shared-pvc
  namespace: tp-app
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  storageClassName: nfs-rwx

